### ISSUE TITLE
VM proxy is set to http://proxy.iiit.ac.in:8080 by default.

### ISSUE THREAD

**Issue by bollu** [vlead/ovpl#24]
Discovered this while I was trying to fix [this bug that I was facing](https://github.com/vlead/ovpl/issues/23). The http_proxy is baked as ```http://proxy.iiit.ac.in:8080``` in the VM's that are created by the ```CentOSVZAdapter``` (since they all use the same base image located at ```/vz/template/cache ```. This needs to be changed at some point the future / made declarative IMHO.

**Comment by ecthiender** [comment]
This commit fixes the issue: 435d55a2d2e3510474f384799ad950a74c6df5c7
