### ISSUE TITLE
ovpl does not do a git pull everytime I commit changes to lab sources and try to install the lab again.

### ISSUE THREAD

**Issue by apurv111** [vlead/ovpl#28]
I tried setting up database lab multiple times today after making changes to my labspec.json.
For the first few time I was thinking something wrong with my labspec and continued modifying the same. Later came to know from sripathi, its a known issue. Raising an issue to notify others.

Title explains it all. Discussed with sripathi and anon. Raising an issue for the same.

**Comment by travula** [comment]
#39
