### ISSUE TITLE
Ensure the VMManager service is up on the lab VM before adapterserver returns 'success' for the init_vm. 

### ISSUE THREAD

**Issue by nrchandan** [vlead/ovpl#3]
Ensure the VMManager service is up on the lab VM before adapterserver returns 'success' for the init_vm. 

This will ensure that LabManager.test_lab action which invokes the VMManager for releasing a lab (into test environment) should not fail. 

Currently,  LabManager executes test_lab multiple times and most of the it is successful because the service starts up during this time.

**Comment by ecthiender** [comment]
This is ensured by AWSAdapter's current implementation. Internally it uses one method to check if the service is up, and then only return the control back to the AdapterServer. Maybe that internal method can be part of the BaseAdapter so that all the adapters can leverage the function.
