### ISSUE TITLE
Paths to components are sometimes dynamically deduced, and in some places it is hardcoded

### ISSUE THREAD

**Issue by ecthiender** [vlead/ovpl#41]
Bring consistency to avoid confusion and potential problems regarding paths to components.

For example, in copying OVPL sources, the adapters deduces the path of the OVPL directory and copies them. But in starting VMManager, the path to the VMManager module is hardcoded in a settings.py
All of these can be refactored.

**Comment by ksripathi** [comment]
Done

Code review is pending.....
