### ISSUE TITLE
VMManager service will fail to start if OVPL repo is cloned in some other name

### ISSUE THREAD

**Issue by ecthiender** [vlead/ovpl#42]
VMManager service will fail to start if OVPL repo is cloned in some other name, and appropriate path to VMManager script value is not changed in settings.py. This is tricky, as settings.py is version-controlled changing this file is not a viable solution because it might break other woking code.

This is related to: #41 . Fixing #41 should fix this.

**Comment by ksripathi** [comment]
Done

Code review is pending.....
