### ISSUE TITLE
All the configuration settings specific to each adapter should be in separate files and be part of config directory.

### ISSUE THREAD

**Issue by ecthiender** [vlead/ovpl#43]
All the configuration settings specific to each adapter should be in separate files and be part of config directory. Also, all config files should be sample.

**Comment by travula** [comment]
All the configuration settings specific to each adapter should be in separate files and be part of config directory.  Also, all config files should be sample. 

This issue is related to #46

**Comment by travula** [comment]
Estimated date of completion is:

**Comment by ambikakaul** [comment]
1. Refactoring for CentOSVZAdapter is completed, It is tested too.
2. Separated out configurations for CentOSBridgeVZAdapter and AWSAdapter . 
3. Testing for both to be done today.

**Comment by ambikakaul** [comment]
1. Separated out code from configurations of two adapters - CentOSVZ and   
    CentOSBridgeVZ.
2. Both are tested and code is checked in.

**Comment by ambikakaul** [comment]
Lint Cleanup and testing after that is also done.

**Comment by ambikakaul** [comment]
Apart from AWSAdapter testing, everything else is complete and tested.

**Comment by ambikakaul** [comment]
Issue resolved. Everything is tested too.
