### ISSUE TITLE
Lint cleanup

### ISSUE THREAD

**Issue by travula** [vlead/ovpl#44]
Run a python lint on all the files to clean up code according to PEP8 guidelines.

**Comment by khushpreet-kaur** [comment]
Current Status: 
       modified:   Controller.py
	modified:   LabManager.py
	modified:   Singleton.py
	modified:   State.py
	modified:   VMPoolManager.py
        modified:   __init__.py

Other than these files under ovpl/src are not updated yet.

**Comment by khushpreet-kaur** [comment]
Current Status: All the python files under /ovpl/src are cleaned up according to pep8 code conventions.

	modified:   ControllerServer.py
        modified:   VMPool.py
        modified:   VMPoolServer.py
	modified:   VMProxy.py

**Comment by khushpreet-kaur** [comment]
Current Status: all python files under /ovpl/src/VMManager are done except LabActionRunner.py.

	modified:   ../VMManager/LabActionScript.py
	modified:   ../VMManager/VMManager.py
	modified:   ../VMManager/VMManagerServer.py
	modified:   ../VMManager/__init__.py

**Comment by khushpreet-kaur** [comment]
Current Status: all python files under /ovpl/src/utils are done.

        modified:   client.py
	modified:   envsetup.py
	modified:   execute_commands.py
	modified:   fake_request.py
	modified:   git_commands.py
        modified:   __init__.py

**Comment by khushpreet-kaur** [comment]
Current Status:  All python files under /src/http_logging are done except http_logging_server.py

modified:   __init__.py
modified:   helper.py
modified:   http_logger.py
modified:   test/test.py

**Comment by khushpreet-kaur** [comment]
Current Status: First round for lint clean up is done for all the python files under /src. 
Final modified files are:
 
modified: http_logging_server.py
modified: CentOSVZAdapter.py
modified: DummyAdapter.

TODO: Lint cleanup for CentOSBridgedNetwork.py (As first round of Lint clean up)

**Comment by khushpreet-kaur** [comment]
One more python file under /script (containers_destroy.py) is done.

Current status: Tests for CentOSVZAdapter, AWSAdapter is done. 

modified: test_CentOSVZAdapter.py
modifiesd __init__.py

- Tests for AWSAdapter is already cleaned up along with implementation by Anon and Ambika.
- Test for CentOSBridgedNetwork needs to be done.

**Comment by khushpreet-kaur** [comment]
CentOSBridgeVZAdapter.py  and test_CentOSBridgeVZAdapter.py is implemented by Sripathi and Prakash. 
So, assigning these files to Sripathi.

**Comment by khushpreet-kaur** [comment]
Current status: Implementation and testing is done. code is pushed to develop branch. 

Need to test after merging this to master branch.

**Comment by khushpreet-kaur** [comment]
CentOSBridgeVZAdapter is pending.
