### ISSUE TITLE
ADS does not pull the latest changes once lab is re-deployed

### ISSUE THREAD

**Issue by khushpreet-kaur** [vlead/ovpl#67]
If test gets failed during lab deployment, ADS does not pull the latest changes of lab's code/repo from github. It uses the same existing repository again for deployment instead of updated one. This needs to be fixed.

**Comment by ecthiender** [comment]
When ADS has deployed a lab, and the lab needs to be redeployed with
updated changes, ADS doesn't pull the latest changes.

It seems like, ADS just uses the lab from the local cache it maintains.
This also hampers the testing and development process, as it leads to
un-understandable and misleading errors.

**Comment by travula** [comment]
Fixed
