### ISSUE TITLE
ADS issue when deploying LdD server using centos-6.9 template on base4 machine

### ISSUE THREAD

**Issue by kraghupathi** [vlead/ovpl#78]
Please follow the [link](https://github.com/vlead/vlabs-learn-by-doing/issues/1). Kindly help to fix this issue as soon as possible.

**Comment by ksripathi** [comment]
work is in progress implemented the code part test cases are in progress shall update here as soon as it finishes

**Comment by ksripathi** [comment]
ADS is functioning to support centos templates.

**Comment by ksripathi** [comment]
@kraghupathi 

Now you can use ADS on base4 machine to deploy the centos based labs/services
