### ISSUE TITLE
Create CentOS6.9 x86_64 template for ADS to support and install services/labs

### ISSUE THREAD

**Issue by ksripathi** [vlead/ovpl#79]
Currently ADS service's centos_bridge adapter is functioning (can deploy labs/services) only with ubuntu vms/containers there is no provision to install labs/services which runs on centos.

Adapter functionality has to be enhanced to support centos as well

**Comment by kraghupathi** [comment]
@ksripathi : Created a **centos-6.9-x86-64-with-emacs** template on Base4 machine and also installed tornado, pip and emacs.

Also tested running make file for feedback portal and its woking.

**Comment by ksripathi** [comment]
CentOS container is created based on lab-specifications data using ADS. Container is unable to ping external network there is an issue connecting to internet

@shashankviswanadha 
Can you please look into it

**Comment by ksripathi** [comment]
above issue refers to @sivashankerN

**Comment by ksripathi** [comment]
Resolved issue by removing bridge related configuration in /etc/sysconfig/network file
