### ISSUE TITLE
Add feature to ADS: Pull the changes from repository.

### ISSUE THREAD

**Issue by sivashankerN** [vlead/ovpl#80]
Feature for ADS:  

**Current issue with ADS setup**: If we want to deploy same lab again ( once it is hosted/deployed using ADS) and again, ( present situation) we have to remove/delete corresponding repository instead of pulling changes made in the repository. Then only we are able to deploy same lab again using ADS. 

**Feature** :
Instead of deleting ( manually ) corresponding lab repository in ADS server( ~/labs/ directory), it would be good just pulling changes made in the repository. 

**Additional Feature (OPTIONAL)** :  Having a backup  of existing repository with the date as an extension.

**Comment by sivashankerN** [comment]
@travula @ksripathi @madhavipuliraju

**Comment by ksripathi** [comment]
Git version  > 1.7 version provides easy way to pull the existing repository usings **-C** argument

git  -C /path pull remote branch

we should upgrade git version in all ADS machines to support git pull functionality

**Comment by ksripathi** [comment]
Reference : https://stackoverflow.com/questions/9155653/git-pull-and-specify-directory

**Comment by ksripathi** [comment]
This issue is fixed and it will be available in next release of ADS
