### ISSUE TITLE
Unable to deploy footer service on Base1 machine using ADS

### ISSUE THREAD

**Issue by kraghupathi** [vlead/ovpl#86]
Unable to deploy footer-service on Base1 machine using ADS, while deploying footer-service it will getting following error
`10/09/2017 01:09:54 AM: DEBUG: /root/ovpl/src/utils/execute_commands.py:28  -> command: git --git-dir=/root/labs//.git --work-tree=/root/labs/ reset --hard
10/09/2017 01:09:54 AM: ERROR: /root/ovpl/src/utils/git_commands.py:81  -> Error Resetting the repository: 'CalledProcessError' object has no attribute 'output'
10/09/2017 01:09:54 AM: ERROR: /root/ovpl/src/lab_manager.py:36  -> Error: 'CalledProcessError' object has no attribute 'output'
10/09/2017 01:09:54 AM: ERROR: /root/ovpl/src/controller.py:89  -> test_lab(): Test failed with error: 'CalledProcessError' object has no attribute 'output'`

Please fix above issue as soon as possible.

**Comment by ksripathi** [comment]
Resolved by restarting the services

**Comment by kraghupathi** [comment]
@ksripathi : 
Please mention the steps, what you fixed in ADS.
