### ISSUE TITLE
Error : 500, Could not connect to localhost:27017

### ISSUE THREAD

**Issue by mrikum7** [vlead/ovpl#91]
I'm receiving this error while downloading the git repository of the virtual lab. Here is the log of it.

DEBUG in api [/var/www/html/ads-web-app/api.py:54]:
lab_id = 1, lab_src_url=https://github.com/virtual-labs/virtual-microwave-laboratory-dei.git, version=master, key=asdahosfnwnskcskoswo, 
--------------------------------------------------------------------------------
[E 180212 11:59:36 web:1030] Uncaught exception POST / (127.0.0.1)
    HTTPRequest(protocol='http', host='localhost:5000', method='POST', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', body='{"lab_id": "1", "version": "master", "current_user": "mrikum7@gmail.com", "key": "asdahosfnwnskcskoswo", "lab_src_url": "https://github.com/virtual-labs/virtual-microwave-laboratory-dei.git"}', headers={'Content-Length': '191', 'Host': 'localhost:5000', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/json', 'Connection': 'keep-alive', 'Accept': 'text/plain', 'User-Agent': 'python-requests/2.18.4'})
    Traceback (most recent call last):
      File "/usr/lib/python2.6/site-packages/tornado/web.py", line 987, in _execute
        getattr(self, self.request.method.lower())(*args, **kwargs)
      File "src/controller_server.py", line 48, in post
        c = Controller()
      File "/root/ovpl/src/controller.py", line 29, in __init__
        self.state = State.Instance()
      File "/root/ovpl/src/singleton.py", line 34, in Instance
        self._instance = self._decorated()
      File "/root/ovpl/src/state.py", line 53, in __init__
        self.db = pymongo.MongoClient().ovpl
      File "/usr/lib64/python2.6/site-packages/pymongo/mongo_client.py", line 337, in __init__
        raise ConnectionFailure(str(e))
    ConnectionFailure: could not connect to localhost:27017: [Errno 111] Connection refused
[E 180212 11:59:36 web:1392] 500 POST / (127.0.0.1) 1.35ms
127.0.0.1 - - [12/Feb/2018 11:59:36] "POST / HTTP/1.1" 200 -

**Comment by ksripathi** [comment]
@mrikum7 

Still it is throwing same error ?

**Comment by mrikum7** [comment]
No it is not. I upgraded the python packages that solved that problem.
